"""Create spot and review tables

Revision ID: 51bbc429a025
Revises: 18fd1ce4e42d
Create Date: 2024-09-26 23:24:17.618718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bbc429a025'
down_revision = '18fd1ce4e42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_name', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('coordinate', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('thum_image', sa.Text(), nullable=True),
    sa.Column('staying_time', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Integer(), nullable=False),
    sa.Column('spot_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('report', sa.Integer(), nullable=True),
    sa.Column('confirmation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('spot')
    # ### end Alembic commands ###
